# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UIKonf
email: questions@uikonf.com
description: UIKonf is an independent conference in Berlin for serious iOS developers. The last three years were a blast. Looking forward to 2016!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uikonf.com" # the base hostname & protocol for your site
twitter_username: uikonf
github_username:  uikonf

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"


# Build settings
markdown: kramdown

# Author details
authors:
  ekurutepe:
    name: Engin Kurutepe
    twitter: http://twitter.com/ekurutepe
    thumbImg: Engin.jpg
  basine:
    name: Sabine Geithner
    twitter: http://twitter.com/sabinegeithner
    thumbImg: sabine.jpg
  mzaks:
    name: Maxim Zaks
    twitter: https://twitter.com/icex33
    thumbImg: Maxim.jpg
  chriseidhof:
    name: Chris Eidhof
    twitter: https://twitter.com/chriseidhof
    thumbImg: chris_thumb.jpg