# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UIKonf
email: questions@uikonf.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/uikonf/uikonf" # the subpath of your site, e.g. /blog
url: "http://clients.antonellatezza.com/" # the base hostname & protocol for your site
twitter_username: uikonf
github_username:  jekyll

# Build settings
markdown: kramdown

# Author details
authors:
  engin_kurutepe:
    name: Engin Kurutepe
    twitter: http://twitter.com/ekurutepe
    thumbImg: Engin.jpg
  sabine_geithner:
    name: Sabine Geithner
    twitter: http://twitter.com/sabinegeithner
    thumbImg: Sabine.jpg